### ISSUE TITLE
Fix //Ring

### ISSUE THREAD

**Issue by thatonesimon** [UCSB-CS56-Projects/cs56-android-smoke-signals#14]
If the phone is on vibrate or mute, the ring method may not work, so force it to ring even if the phone is on mute or vibrate.

**Comment by thatonesimon** [comment]
This was fixed in pull request #15, wondering if we can get points for fixing this small bug.

**Comment by jimmylle** [comment]
@thatonesimon So i'm not sure if the ring method is supposed to ring when the phone is on vibrate/mute because the user probably put it on vibrate/mute so that it won't give them notifications and stuff and making the ring method bypass that might not be what they want. Instead you could have a new command or add additional argument to the ring method like "//Ring force" or something so that it force rings the phone because maybe the user can't find their phone and needs it to ring regardless of vibrate/mute. So if you go that route edit this issue to make it clearer about what its changing.

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/15).
